### ISSUE TITLE
Instance of 'Application' has no 'createQmlComponent' member

### ISSUE THREAD

**Issue by CatchZeng** [Ultimaker/UraniumExampleToolPlugin#3]
Which method is the alternative to 'createQmlComponent' in 'Application' ?

**Comment by CatchZeng** [comment]
@Ghostkeeper Is there any good solution?

**Comment by CatchZeng** [comment]
@Ghostkeeper 

I added a log to the event method, but it hasn't been triggered. What is the problem?

```
    def event(self, event):
        # The super event updates the selection if the user clicks on some object.
        super().event(event)

        Logger.log(
            "d", "event method")
       ......
```

**Comment by Ghostkeeper** [comment]
`createQmlComponent` is a method of `UM.Qt.QtApplication.QtApplication`, which extends `UM.Application.Application`. It doesn't exist in `Application`.

The `event` method should trigger when the tool is selected by the user, and then the user clicks on some object in the build plate.

**Comment by Ghostkeeper** [comment]
I'm not getting any of these errors when I try using the plug-in in current master.

**Comment by CatchZeng** [comment]
```
def _createDialogue(self):
        #Create a QML component from the SelectionInfo.qml file.
        qml_file_path = os.path.join(PluginRegistry.getInstance().getPluginPath(self.getPluginId()), "SelectionInfo.qml")
        component = Application.getInstance().createQmlComponent(qml_file_path)
```

In this method, Application is imported from UM.Application, not from UM.Qt.QtApplication, so there will be problems with the createQmlComponent method not being found.

```
from UM.Application import Application
```

**Comment by CatchZeng** [comment]
I loaded the UraniumExampleToolPlugin into cura, as shown in the log below. But where is this tool? How to select it? The picture below is my screenshot.

```
INFO - [MainThread] UM.PluginRegistry.loadPlugin [405]: Loaded plugin UraniumExampleToolPlugin
```

<img width="1235" alt="cura+exampletool" src="https://user-images.githubusercontent.com/10027281/56176326-5ce7ca00-602d-11e9-9247-820398eee5a7.png">

**Comment by CatchZeng** [comment]
I know what happened, thank you for your help.

**Comment by Ghostkeeper** [comment]
`Application.getInstance()` will return the singleton instance, regardless of which subclass of `Application` it is. So in Cura's case it'll return a `CuraApplication` which extends from `QtApplication`.
